// Built-in exercise library and example templates.
// Names follow the common "Movement (Equipment)" convention so a Strong CSV
// import lines up with these entries automatically.
import { slug } from './util.js';

export const CATEGORIES = [
  { id: 'barbell', label: 'Barbell' },
  { id: 'dumbbell', label: 'Dumbbell' },
  { id: 'machine', label: 'Machine / Other' },
  { id: 'weighted_bw', label: 'Weighted bodyweight' },
  { id: 'assisted_bw', label: 'Assisted bodyweight' },
  { id: 'reps', label: 'Reps only' },
  { id: 'cardio', label: 'Cardio (distance + time)' },
  { id: 'duration', label: 'Duration' },
];
export const CATEGORY_LABEL = Object.fromEntries(CATEGORIES.map((c) => [c.id, c.label]));

export const BODY_PARTS = [
  { id: 'chest', label: 'Chest' },
  { id: 'back', label: 'Back' },
  { id: 'shoulders', label: 'Shoulders' },
  { id: 'arms', label: 'Arms' },
  { id: 'legs', label: 'Legs' },
  { id: 'core', label: 'Core' },
  { id: 'full', label: 'Full body' },
  { id: 'cardio', label: 'Cardio' },
  { id: 'other', label: 'Other' },
];
export const BODY_PART_LABEL = Object.fromEntries(BODY_PARTS.map((b) => [b.id, b.label]));

// [name, category, bodyPart]
const B = 'barbell', D = 'dumbbell', M = 'machine', WB = 'weighted_bw', AB = 'assisted_bw',
  R = 'reps', C = 'cardio', T = 'duration';

const LIST = [
  // Chest
  ['Bench Press (Barbell)', B, 'chest'],
  ['Bench Press (Dumbbell)', D, 'chest'],
  ['Bench Press (Smith Machine)', M, 'chest'],
  ['Incline Bench Press (Barbell)', B, 'chest'],
  ['Incline Bench Press (Dumbbell)', D, 'chest'],
  ['Incline Bench Press (Smith Machine)', M, 'chest'],
  ['Decline Bench Press (Barbell)', B, 'chest'],
  ['Decline Bench Press (Dumbbell)', D, 'chest'],
  ['Floor Press (Barbell)', B, 'chest'],
  ['Chest Press (Machine)', M, 'chest'],
  ['Incline Chest Press (Machine)', M, 'chest'],
  ['Chest Fly (Dumbbell)', D, 'chest'],
  ['Incline Chest Fly (Dumbbell)', D, 'chest'],
  ['Chest Fly (Machine)', M, 'chest'],
  ['Cable Crossover (Cable)', M, 'chest'],
  ['Low Cable Fly (Cable)', M, 'chest'],
  ['Pullover (Dumbbell)', D, 'chest'],
  ['Push Up', R, 'chest'],
  ['Incline Push Up', R, 'chest'],
  ['Decline Push Up', R, 'chest'],
  ['Push Up (Weighted)', WB, 'chest'],
  ['Chest Dip', R, 'chest'],
  ['Chest Dip (Weighted)', WB, 'chest'],
  ['Chest Dip (Assisted)', AB, 'chest'],

  // Back
  ['Deadlift (Barbell)', B, 'back'],
  ['Sumo Deadlift (Barbell)', B, 'back'],
  ['Deadlift (Trap Bar)', B, 'back'],
  ['Deadlift (Dumbbell)', D, 'back'],
  ['Rack Pull (Barbell)', B, 'back'],
  ['Bent Over Row (Barbell)', B, 'back'],
  ['Pendlay Row (Barbell)', B, 'back'],
  ['Bent Over One Arm Row (Dumbbell)', D, 'back'],
  ['Chest Supported Row (Dumbbell)', D, 'back'],
  ['T Bar Row', M, 'back'],
  ['Seated Row (Cable)', M, 'back'],
  ['Seated Row (Machine)', M, 'back'],
  ['Lat Pulldown (Cable)', M, 'back'],
  ['Lat Pulldown - Close Grip (Cable)', M, 'back'],
  ['Lat Pulldown (Machine)', M, 'back'],
  ['Straight Arm Pulldown (Cable)', M, 'back'],
  ['Pull Up', R, 'back'],
  ['Pull Up (Weighted)', WB, 'back'],
  ['Pull Up (Assisted)', AB, 'back'],
  ['Chin Up', R, 'back'],
  ['Chin Up (Weighted)', WB, 'back'],
  ['Chin Up (Assisted)', AB, 'back'],
  ['Inverted Row', R, 'back'],
  ['Back Extension', R, 'back'],
  ['Back Extension (Weighted)', WB, 'back'],
  ['Back Extension (Machine)', M, 'back'],
  ['Shrug (Barbell)', B, 'back'],
  ['Shrug (Dumbbell)', D, 'back'],

  // Shoulders
  ['Overhead Press (Barbell)', B, 'shoulders'],
  ['Overhead Press (Dumbbell)', D, 'shoulders'],
  ['Seated Overhead Press (Dumbbell)', D, 'shoulders'],
  ['Seated Overhead Press (Barbell)', B, 'shoulders'],
  ['Shoulder Press (Machine)', M, 'shoulders'],
  ['Shoulder Press (Smith Machine)', M, 'shoulders'],
  ['Arnold Press (Dumbbell)', D, 'shoulders'],
  ['Push Press (Barbell)', B, 'shoulders'],
  ['Landmine Press (Barbell)', B, 'shoulders'],
  ['Lateral Raise (Dumbbell)', D, 'shoulders'],
  ['Lateral Raise (Cable)', M, 'shoulders'],
  ['Lateral Raise (Machine)', M, 'shoulders'],
  ['Front Raise (Dumbbell)', D, 'shoulders'],
  ['Front Raise (Cable)', M, 'shoulders'],
  ['Upright Row (Barbell)', B, 'shoulders'],
  ['Upright Row (Cable)', M, 'shoulders'],
  ['Face Pull (Cable)', M, 'shoulders'],
  ['Reverse Fly (Dumbbell)', D, 'shoulders'],
  ['Reverse Fly (Machine)', M, 'shoulders'],
  ['Reverse Fly (Cable)', M, 'shoulders'],
  ['Handstand Push Up', R, 'shoulders'],

  // Arms
  ['Bicep Curl (Barbell)', B, 'arms'],
  ['Bicep Curl (EZ Bar)', B, 'arms'],
  ['Bicep Curl (Dumbbell)', D, 'arms'],
  ['Bicep Curl (Cable)', M, 'arms'],
  ['Bicep Curl (Machine)', M, 'arms'],
  ['Hammer Curl (Dumbbell)', D, 'arms'],
  ['Hammer Curl (Cable)', M, 'arms'],
  ['Incline Curl (Dumbbell)', D, 'arms'],
  ['Concentration Curl (Dumbbell)', D, 'arms'],
  ['Preacher Curl (Barbell)', B, 'arms'],
  ['Preacher Curl (Dumbbell)', D, 'arms'],
  ['Preacher Curl (Machine)', M, 'arms'],
  ['Reverse Curl (Barbell)', B, 'arms'],
  ['Triceps Pushdown (Cable)', M, 'arms'],
  ['Triceps Pushdown - Rope (Cable)', M, 'arms'],
  ['Overhead Triceps Extension (Cable)', M, 'arms'],
  ['Overhead Triceps Extension (Dumbbell)', D, 'arms'],
  ['Triceps Extension (Machine)', M, 'arms'],
  ['Skullcrusher (Barbell)', B, 'arms'],
  ['Skullcrusher (Dumbbell)', D, 'arms'],
  ['Close Grip Bench Press (Barbell)', B, 'arms'],
  ['Triceps Kickback (Dumbbell)', D, 'arms'],
  ['Triceps Dip', R, 'arms'],
  ['Triceps Dip (Weighted)', WB, 'arms'],
  ['Triceps Dip (Assisted)', AB, 'arms'],
  ['Bench Dip', R, 'arms'],
  ['Wrist Curl (Dumbbell)', D, 'arms'],
  ['Wrist Curl (Barbell)', B, 'arms'],
  ['Reverse Wrist Curl (Dumbbell)', D, 'arms'],

  // Legs
  ['Squat (Barbell)', B, 'legs'],
  ['Front Squat (Barbell)', B, 'legs'],
  ['Squat (Smith Machine)', M, 'legs'],
  ['Hack Squat (Machine)', M, 'legs'],
  ['Pendulum Squat (Machine)', M, 'legs'],
  ['Leg Press (Machine)', M, 'legs'],
  ['Goblet Squat (Dumbbell)', D, 'legs'],
  ['Goblet Squat (Kettlebell)', M, 'legs'],
  ['Squat (Bodyweight)', R, 'legs'],
  ['Pistol Squat', R, 'legs'],
  ['Bulgarian Split Squat (Dumbbell)', D, 'legs'],
  ['Bulgarian Split Squat (Barbell)', B, 'legs'],
  ['Lunge (Dumbbell)', D, 'legs'],
  ['Lunge (Barbell)', B, 'legs'],
  ['Walking Lunge (Dumbbell)', D, 'legs'],
  ['Lunge', R, 'legs'],
  ['Step Up (Dumbbell)', D, 'legs'],
  ['Romanian Deadlift (Barbell)', B, 'legs'],
  ['Romanian Deadlift (Dumbbell)', D, 'legs'],
  ['Stiff Leg Deadlift (Barbell)', B, 'legs'],
  ['Good Morning (Barbell)', B, 'legs'],
  ['Leg Extension (Machine)', M, 'legs'],
  ['Lying Leg Curl (Machine)', M, 'legs'],
  ['Seated Leg Curl (Machine)', M, 'legs'],
  ['Nordic Hamstring Curl', R, 'legs'],
  ['Hip Thrust (Barbell)', B, 'legs'],
  ['Hip Thrust (Machine)', M, 'legs'],
  ['Glute Bridge', R, 'legs'],
  ['Glute Kickback (Cable)', M, 'legs'],
  ['Glute Kickback (Machine)', M, 'legs'],
  ['Hip Abduction (Machine)', M, 'legs'],
  ['Hip Adduction (Machine)', M, 'legs'],
  ['Standing Calf Raise (Machine)', M, 'legs'],
  ['Seated Calf Raise (Machine)', M, 'legs'],
  ['Calf Press on Leg Press (Machine)', M, 'legs'],
  ['Calf Raise (Dumbbell)', D, 'legs'],
  ['Box Jump', R, 'legs'],

  // Core
  ['Crunch', R, 'core'],
  ['Crunch (Machine)', M, 'core'],
  ['Cable Crunch (Cable)', M, 'core'],
  ['Decline Crunch', R, 'core'],
  ['Sit Up', R, 'core'],
  ['Bicycle Crunch', R, 'core'],
  ['Hanging Leg Raise', R, 'core'],
  ['Hanging Knee Raise', R, 'core'],
  ['Lying Leg Raise', R, 'core'],
  ['Toes to Bar', R, 'core'],
  ['Ab Wheel', R, 'core'],
  ['Russian Twist', R, 'core'],
  ['Russian Twist (Weighted)', WB, 'core'],
  ['Mountain Climber', R, 'core'],
  ['Dead Bug', R, 'core'],
  ['Pallof Press (Cable)', M, 'core'],
  ['Wood Chop (Cable)', M, 'core'],
  ['Plank', T, 'core'],
  ['Side Plank', T, 'core'],
  ['Hollow Hold', T, 'core'],
  ['L-Sit', T, 'core'],

  // Full body / Olympic
  ['Clean (Barbell)', B, 'full'],
  ['Power Clean (Barbell)', B, 'full'],
  ['Hang Clean (Barbell)', B, 'full'],
  ['Clean and Jerk (Barbell)', B, 'full'],
  ['Snatch (Barbell)', B, 'full'],
  ['Power Snatch (Barbell)', B, 'full'],
  ['Thruster (Barbell)', B, 'full'],
  ['Kettlebell Swing', M, 'full'],
  ['Turkish Get Up (Kettlebell)', M, 'full'],
  ['Farmer\'s Walk (Dumbbell)', D, 'full'],
  ['Burpee', R, 'full'],
  ['Battle Ropes', T, 'full'],
  ['Sled Push', M, 'full'],

  // Cardio
  ['Running', C, 'cardio'],
  ['Running (Treadmill)', C, 'cardio'],
  ['Walking', C, 'cardio'],
  ['Incline Walk (Treadmill)', C, 'cardio'],
  ['Cycling', C, 'cardio'],
  ['Cycling (Indoor)', C, 'cardio'],
  ['Rowing (Machine)', C, 'cardio'],
  ['Elliptical Trainer', C, 'cardio'],
  ['Stair Climber', T, 'cardio'],
  ['Ski Erg', C, 'cardio'],
  ['Air Bike', C, 'cardio'],
  ['Swimming', C, 'cardio'],
  ['Hiking', C, 'cardio'],
  ['Jump Rope', T, 'cardio'],

  // Other
  ['Stretching', T, 'other'],
  ['Yoga', T, 'other'],
  ['Warm Up', T, 'other'],
];

export const SEED_VERSION = 1;

export const SEED_EXERCISES = LIST.map(([name, category, bodyPart]) => ({
  id: 'x-' + slug(name),
  name,
  category,
  bodyPart,
  builtin: true,
}));

// Example templates. Sets: [type, reps] — weights stay empty so the app shows
// your own previous numbers once you have them.
const ex = (name, sets, reps, restSec) => ({
  exerciseId: 'x-' + slug(name),
  restSec,
  sets: Array.from({ length: sets }, () => ({ type: 'normal', r: reps })),
});

export const EXAMPLE_TEMPLATES = [
  {
    id: 'example-push', name: 'Push', folder: 'Push / Pull / Legs', example: true,
    exercises: [
      ex('Bench Press (Barbell)', 3, 8, 150),
      ex('Incline Bench Press (Dumbbell)', 3, 10, 120),
      ex('Seated Overhead Press (Dumbbell)', 3, 10, 120),
      ex('Lateral Raise (Dumbbell)', 3, 15, 60),
      ex('Triceps Pushdown - Rope (Cable)', 3, 12, 60),
    ],
  },
  {
    id: 'example-pull', name: 'Pull', folder: 'Push / Pull / Legs', example: true,
    exercises: [
      ex('Deadlift (Barbell)', 3, 5, 180),
      ex('Lat Pulldown (Cable)', 3, 10, 120),
      ex('Seated Row (Cable)', 3, 10, 120),
      ex('Face Pull (Cable)', 3, 15, 60),
      ex('Bicep Curl (Dumbbell)', 3, 12, 60),
    ],
  },
  {
    id: 'example-legs', name: 'Legs', folder: 'Push / Pull / Legs', example: true,
    exercises: [
      ex('Squat (Barbell)', 3, 6, 180),
      ex('Romanian Deadlift (Barbell)', 3, 8, 150),
      ex('Leg Press (Machine)', 3, 10, 120),
      ex('Lying Leg Curl (Machine)', 3, 12, 90),
      ex('Standing Calf Raise (Machine)', 4, 12, 60),
    ],
  },
  {
    id: 'example-5x5-a', name: 'Strength A', folder: 'Strength 5×5', example: true,
    exercises: [
      ex('Squat (Barbell)', 5, 5, 180),
      ex('Bench Press (Barbell)', 5, 5, 180),
      ex('Bent Over Row (Barbell)', 5, 5, 180),
    ],
  },
  {
    id: 'example-5x5-b', name: 'Strength B', folder: 'Strength 5×5', example: true,
    exercises: [
      ex('Squat (Barbell)', 5, 5, 180),
      ex('Overhead Press (Barbell)', 5, 5, 180),
      ex('Deadlift (Barbell)', 1, 5, 180),
    ],
  },
  {
    id: 'example-full', name: 'Full Body', folder: 'Full body', example: true,
    exercises: [
      ex('Goblet Squat (Dumbbell)', 3, 10, 90),
      ex('Bench Press (Dumbbell)', 3, 10, 90),
      ex('Bent Over One Arm Row (Dumbbell)', 3, 10, 90),
      ex('Hip Thrust (Barbell)', 3, 10, 90),
      { exerciseId: 'x-plank', restSec: 60, sets: [{ type: 'normal', t: 45 }, { type: 'normal', t: 45 }] },
    ],
  },
];

export const MEASUREMENTS = [
  { id: 'bodyweight', label: 'Body weight', kind: 'weight', group: 'core' },
  { id: 'bodyfat', label: 'Body fat', kind: 'percent', group: 'core' },
  { id: 'calories', label: 'Calorie intake', kind: 'kcal', group: 'core' },
  { id: 'neck', label: 'Neck', kind: 'length', group: 'body' },
  { id: 'shoulders', label: 'Shoulders', kind: 'length', group: 'body' },
  { id: 'chest', label: 'Chest', kind: 'length', group: 'body' },
  { id: 'bicep_l', label: 'Left biceps', kind: 'length', group: 'body' },
  { id: 'bicep_r', label: 'Right biceps', kind: 'length', group: 'body' },
  { id: 'forearm_l', label: 'Left forearm', kind: 'length', group: 'body' },
  { id: 'forearm_r', label: 'Right forearm', kind: 'length', group: 'body' },
  { id: 'waist', label: 'Waist', kind: 'length', group: 'body' },
  { id: 'hips', label: 'Hips', kind: 'length', group: 'body' },
  { id: 'thigh_l', label: 'Left thigh', kind: 'length', group: 'body' },
  { id: 'thigh_r', label: 'Right thigh', kind: 'length', group: 'body' },
  { id: 'calf_l', label: 'Left calf', kind: 'length', group: 'body' },
  { id: 'calf_r', label: 'Right calf', kind: 'length', group: 'body' },
];
export const MEASUREMENT_BY_ID = Object.fromEntries(MEASUREMENTS.map((m) => [m.id, m]));
